### ISSUE TITLE
希望有3.x版本 以及把回复的评论内容也列出来

### ISSUE THREAD

**Issue by lightbrush** [pengshiqi/NetEaseMusicCrawl#1]
1. 尝试了下将您的py2版本代码转成py3，发现比较困难，无果……

2. 有些热评是对某条评论的回复，我看了下返还的数据里是包含了相关信息的，感觉可以在最终结果里补充上（这样的小事俺就不发PR了把hh）。

非常感谢您的代码~

**Comment by pengshiqi** [comment]
感谢你的issue，我新增了一个名为python3.5的branch，是python3.5版本的程序，可以运行出一样的结果。
从py2到py3主要的变化就是python3中的bytes类型和str类型的转换，可以通过.encode('utf-8')和.decode('utf-8')来解决。

**Comment by lightbrush** [comment]
谢谢！我也是昨天被这个转换搞得糊涂了 hh
